### PR TITLE
Default CR is using async - comment router field

### PR DESCRIPTION
**Pull request by an3l**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/init-deploy.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/users.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/limits.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/demand-backup.log) |
| gr-init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/9fda0d5/gr-init-deploy.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/128/commits/9fda0d570f228c6306ccf07d50a47b9487c96b8a
image: `perconalab/percona-server-mysql-operator:PR-128-9fda0d5`

**Comment by egegunes** [comment]
@tplavcic what do you think about this one?

**Comment by tplavcic** [comment]
> @tplavcic what do you think about this one?

@egegunes Well if we look at the PXC there we have:
```
  proxysql:
    enabled: false
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:main-proxysql
```
so it is not default and is not commented although there we have `enabled: false` so I guess it's not completely the same.
Since currently we don't support switching between GR and async I think it's ok to merge this so I will approve it and if it proves to make problems down the line we can uncomment later.

**Review by hors — CHANGES_REQUESTED** [review]
All changes connected with CR should be approved by our PM @spron-in .

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/auto-config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/demand-backup.log) |
| gr-init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/gr-init-deploy.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/config.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/monitoring.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/scaling.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/semi-sync.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/users.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-128/ae912f6/limits.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/128/commits/ae912f676f42ce84313e7464d9b079d14221c246
image: `perconalab/percona-server-mysql-operator:PR-128-ae912f6`

**Comment by spron-in** [comment]
I don't believe we should be doing this.
1) we plan to use group replication by default in this operator moving forward, keeping async as an option
2) we do not comment some of the sections intentionally to maintain simpler onboarding (we do similar thing in other operators)

@an3l I understand that you want to adopt our operator for MariaDB which does not support group replication, but it contradicts with (1) for us.

**Comment by an3l** [comment]
Sure, thanks for clarification.

**Pull request closed without merging**
