### PR TITLE
K8SPS-334: add prefix to finalizers

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPS-334](https://jira.percona.com/browse/K8SPS-334) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://perconadev.atlassian.net/browse/K8SPS-334

**DESCRIPTION**
---
This PR renames finalizers:

- `delete-mysql-pods-in-order` => `percona.com/delete-mysql-pods-in-order` 
- `delete-ssl` => `percona.com/delete-ssl`
- `delete-backup` => `percona.com/delete-backup` 

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [x] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [x] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [x] Is an E2E test/test case added for the new feature/change?
- [x] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [x] Are all needed new/changed options added to default YAML files?
- [x] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [x] Does the change support oldest and newest supported PS version?
- [x] Does the change support oldest and newest supported Kubernetes version?

[K8SPS-334]: https://perconadev.atlassian.net/browse/K8SPS-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| async-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/async-ignore-annotations.log) |
| auto-config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/auto-config.log) |
| config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/config.log) |
| config-router | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/config-router.log) |
| demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/demand-backup.log) |
| gr-demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-demand-backup.log) |
| gr-demand-backup-haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-demand-backup-haproxy.log) |
| gr-haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-haproxy.log) |
| gr-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-ignore-annotations.log) |
| gr-init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-init-deploy.log) |
| gr-one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-one-pod.log) |
| gr-recreate | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-recreate.log) |
| gr-scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-scaling.log) |
| gr-security-context | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-security-context.log) |
| gr-self-healing | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-self-healing.log) |
| gr-tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-tls-cert-manager.log) |
| gr-users | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/gr-users.log) |
| haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/haproxy.log) |
| init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/init-deploy.log) |
| limits | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/limits.log) |
| monitoring | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/monitoring.log) |
| one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/one-pod.log) |
| operator-self-healing | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/operator-self-healing.log) |
| recreate | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/recreate.log) |
| scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/scaling.log) |
| service-per-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/service-per-pod.log) |
| sidecars | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/sidecars.log) |
| smart-update | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/smart-update.log) |
| tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/tls-cert-manager.log) |
| users | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/users.log) |
| version-service | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/fbc14011/version-service.log) |
| We run 0 out of 31|

commit: https://github.com/percona/percona-server-mysql-operator/pull/655/commits/fbc140119fbc7f51505a4f068417892a4890f79b
image: `perconalab/percona-server-mysql-operator:PR-655-fbc14011`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| async-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/async-ignore-annotations.log) |
| auto-config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/auto-config.log) |
| config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/config.log) |
| config-router | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/config-router.log) |
| demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/demand-backup.log) |
| gr-demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-demand-backup.log) |
| gr-demand-backup-haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-demand-backup-haproxy.log) |
| gr-haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-haproxy.log) |
| gr-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-ignore-annotations.log) |
| gr-init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-init-deploy.log) |
| gr-one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-one-pod.log) |
| gr-recreate | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-recreate.log) |
| gr-scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-scaling.log) |
| gr-security-context | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-security-context.log) |
| gr-self-healing | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-self-healing.log) |
| gr-tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-tls-cert-manager.log) |
| gr-users | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/gr-users.log) |
| haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/haproxy.log) |
| init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/init-deploy.log) |
| limits | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/limits.log) |
| monitoring | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/monitoring.log) |
| one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/one-pod.log) |
| operator-self-healing | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/operator-self-healing.log) |
| recreate | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/recreate.log) |
| scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/scaling.log) |
| service-per-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/service-per-pod.log) |
| sidecars | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/sidecars.log) |
| smart-update | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/smart-update.log) |
| tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/tls-cert-manager.log) |
| users | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/users.log) |
| version-service | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/baf1907d/version-service.log) |
| We run 0 out of 31|

commit: https://github.com/percona/percona-server-mysql-operator/pull/655/commits/baf1907dc3086a011c85c2d8dd9eac0be17c8781
image: `perconalab/percona-server-mysql-operator:PR-655-baf1907d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| async-ignore-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/async-ignore-annotations.log) |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/config.log) |
| config-router | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/config-router.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/demand-backup.log) |
| gr-demand-backup | [failure](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-demand-backup.log) |
| gr-demand-backup-haproxy | [failure](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-demand-backup-haproxy.log) |
| gr-haproxy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-haproxy.log) |
| gr-ignore-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-ignore-annotations.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-init-deploy.log) |
| gr-one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-one-pod.log) |
| gr-recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-recreate.log) |
| gr-scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-scaling.log) |
| gr-security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-security-context.log) |
| gr-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-self-healing.log) |
| gr-tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-tls-cert-manager.log) |
| gr-users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/gr-users.log) |
| haproxy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/haproxy.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/init-deploy.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/limits.log) |
| monitoring | [failure](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/monitoring.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/one-pod.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/operator-self-healing.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/recreate.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/scaling.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/sidecars.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/smart-update.log) |
| tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/tls-cert-manager.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/users.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/c654524a/version-service.log) |
| We run 31 out of 31|

commit: https://github.com/percona/percona-server-mysql-operator/pull/655/commits/c654524aa27bf799aebf951dd3cc3191bafe025f
image: `perconalab/percona-server-mysql-operator:PR-655-c654524a`

**Review by hors — CHANGES_REQUESTED** [review]
@pooknull I think we need to rename it https://github.com/percona/percona-server-mysql-operator/blob/main/deploy/backup.yaml#L6 as well

**Review by egegunes — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| async-ignore-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/async-ignore-annotations.log) |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/config.log) |
| config-router | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/config-router.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/demand-backup.log) |
| gr-demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-demand-backup.log) |
| gr-demand-backup-haproxy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-demand-backup-haproxy.log) |
| gr-haproxy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-haproxy.log) |
| gr-ignore-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-ignore-annotations.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-init-deploy.log) |
| gr-one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-one-pod.log) |
| gr-recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-recreate.log) |
| gr-scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-scaling.log) |
| gr-security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-security-context.log) |
| gr-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-self-healing.log) |
| gr-tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-tls-cert-manager.log) |
| gr-users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/gr-users.log) |
| haproxy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/haproxy.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/init-deploy.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/limits.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/monitoring.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/one-pod.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/operator-self-healing.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/recreate.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/scaling.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/sidecars.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/smart-update.log) |
| tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/tls-cert-manager.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/users.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-655/a0c1d990/version-service.log) |
| We run 31 out of 31|

commit: https://github.com/percona/percona-server-mysql-operator/pull/655/commits/a0c1d9905f1c00960716241af4cec90d909b2a33
image: `perconalab/percona-server-mysql-operator:PR-655-a0c1d990`

**Review by hors — APPROVED** [review]

**Review by egegunes — APPROVED** [review]

**Pull request merged**
