### PR TITLE
Build custom resource locally 

### PR DESCRIPTION
**Pull request by an3l**
Hi,
there is no description how to build the operator and have CRs visible in K8s (minikube). 
I tried to do some tweaks and output is successful
<details> <summary> Before patch </summary> 
<pre>
$ make
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen crd rbac:roleName=percona-server-mysql-operator webhook paths="./..." output:crd:artifacts:config=config/crd/bases  ## Generate WebhookConfiguration, Role and CustomResourceDefinition objects.
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen object:headerFile="LICENSE-HEADER" paths="./..." ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
ROOT_REPO=/home/anel/percona/percona-server-mysql-operator VERSION=anel-try-to-build /home/anel/percona/percona-server-mysql-operator/e2e-tests/build
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   500  100   500    0     0   1766      0 --:--:-- --:--:-- --:--:--  1760
~/percona/percona-server-mysql-operator ~/percona/percona-server-mysql-operator
"--squash" is only supported on a Docker daemon with experimental features enabled
~/percona/percona-server-mysql-operator
The push refers to repository [docker.io/perconalab/percona-server-mysql-operator]
tag does not exist: perconalab/percona-server-m
</pre>
</details>
<details><summary>Build with patch</summary>
    <pre>
$ make install
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen crd rbac:roleName=percona-server-mysql-operator webhook paths="./..." output:crd:artifacts:config=config/crd/bases  ## Generate WebhookConfiguration, Role and CustomResourceDefinition objects.
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen object:headerFile="LICENSE-HEADER" paths="./..." ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/crd/ > ./deploy/crd.yaml
echo "---" >> ./deploy/crd.yaml
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/rbac/ | sed 's/ClusterRole/Role/g' > ./deploy/rbac.yaml
echo "---" >> ./deploy/rbac.yaml
cd config/manager && /home/anel/percona/percona-server-mysql-operator/bin/kustomize edit set image perconalab/percona-server-mysql-operator=perconalab/percona-server-mysql-operator:anel-try-to-build
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/manager/ > ./deploy/operator.yaml
echo "---" >> ./deploy/operator.yaml
cat ./deploy/crd.yaml ./deploy/rbac.yaml ./deploy/operator.yaml > ./deploy/bundle.yaml
kubectl apply -f ./deploy/crd.yaml
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlbackups.ps.percona.com created
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlrestores.ps.percona.com created
customresourcedefinition.apiextensions.k8s.io/perconaservermysqls.ps.percona.com created
kubectl apply -f ./deploy/rbac.yaml
serviceaccount/percona-server-mysql-operator created
role.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection created
role.rbac.authorization.k8s.io/percona-server-mysql-operator created
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection created
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator created
    </pre>
  </details>

<details><summary>Show CRDs after build</summary>
    <pre>
$ kubectl get crds -o wide
NAME                                        CREATED AT
perconaservermysqlbackups.ps.percona.com    2022-06-08T11:56:33Z
perconaservermysqlrestores.ps.percona.com   2022-06-08T11:56:33Z
perconaservermysqls.ps.percona.com          2022-06-08T11:56:33Z
    </pre>
   </details>

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/46376cb/users.log) |
| We run 8 out of 8|

commit: https://github.com/percona/percona-server-mysql-operator/pull/81/commits/46376cb2f4d111dabf9d5dd596989226bd10bc9a
image: `perconalab/percona-server-mysql-operator:PR-81-46376cb`

**Comment by egegunes** [comment]
Hi @an3l, thank you for your contribution. https://github.com/percona/percona-server-mysql-operator/pull/81/commits/72bbfb20d540e7bf995a351beb4e1cb750ca4182 LGTM but https://github.com/percona/percona-server-mysql-operator/pull/81/commits/46376cb2f4d111dabf9d5dd596989226bd10bc9a will break our development workflow. Any chance to set use these env variables to disable squashing and pushing when you build?

**Comment by an3l** [comment]
Hi @egegunes, yes sure, updated.
Do you have any documentation about building this operator or any other internals related to the development of operator?
This is what happens to me locally:
```bash
$ make  # build binaries
...
 ---> 3de4bd3c49d1
Step 21/23 : COPY build/ps-entrypoint.sh /ps-entrypoint.sh
 ---> 99761cea5339
Step 22/23 : COPY build/ps-init-entrypoint.sh /ps-init-entrypoint.sh
 ---> 6712f2891179
Step 23/23 : USER 2
 ---> Running in e26a18749566
Removing intermediate container e26a18749566
 ---> 51cdb240e109
[Warning] One or more build-args [GIT_BRANCH] were not consumed
Successfully built 51cdb240e109
Successfully tagged perconalab/percona-server-mysql-operator:anel-try-to-build
~/percona/percona-server-mysql-operator

$ kubectl get secrets # why this secret is created during building of binary?
percona-server-mysql-operator-token-clks8   kubernetes.io/service-account-token   3      2m32s
$ make install # will install crds to minikube
$ kubectl get ps
$ kubectl get crds
No resources found
$ make install
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/kustomize/kustomize/v4@v4.5.3
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen crd rbac:roleName=percona-server-mysql-operator webhook paths="./..." output:crd:artifacts:config=config/crd/bases  ## Generate WebhookConfiguration, Role and CustomResourceDefinition objects.
/home/anel/percona/percona-server-mysql-operator/bin/controller-gen object:headerFile="LICENSE-HEADER" paths="./..." ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/crd/ > ./deploy/crd.yaml
echo "---" >> ./deploy/crd.yaml
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/rbac/ | sed 's/ClusterRole/Role/g' > ./deploy/rbac.yaml
echo "---" >> ./deploy/rbac.yaml
cd config/manager && /home/anel/percona/percona-server-mysql-operator/bin/kustomize edit set image perconalab/percona-server-mysql-operator=perconalab/percona-server-mysql-operator:anel-try-to-build
/home/anel/percona/percona-server-mysql-operator/bin/kustomize build config/manager/ > ./deploy/operator.yaml
echo "---" >> ./deploy/operator.yaml
cat ./deploy/crd.yaml ./deploy/rbac.yaml ./deploy/operator.yaml > ./deploy/bundle.yaml
kubectl apply -f ./deploy/crd.yaml
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlbackups.ps.percona.com created
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlrestores.ps.percona.com created
customresourcedefinition.apiextensions.k8s.io/perconaservermysqls.ps.percona.com created
kubectl apply -f ./deploy/rbac.yaml
serviceaccount/percona-server-mysql-operator unchanged
role.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection unchanged
role.rbac.authorization.k8s.io/percona-server-mysql-operator configured
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection unchanged
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator unchanged
$ kubectl get crds
NAME                                        CREATED AT
perconaservermysqlbackups.ps.percona.com    2022-06-10T12:29:29Z
perconaservermysqlrestores.ps.percona.com   2022-06-10T12:29:29Z
perconaservermysqls.ps.percona.com          2022-06-10T12:29:29Z
$ kubectl apply -f ./deploy/cr.yaml 
perconaservermysql.ps.percona.com/cluster1 created
$ kubectl get ps
NAME       MYSQL   ORCHESTRATOR   STATE   AGE
cluster1                                  22s

$ kubectl apply -f ./deploy/bundle.yaml  # this will just add config-maps and start operator
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlbackups.ps.percona.com configured
customresourcedefinition.apiextensions.k8s.io/perconaservermysqlrestores.ps.percona.com configured
customresourcedefinition.apiextensions.k8s.io/perconaservermysqls.ps.percona.com configured
serviceaccount/percona-server-mysql-operator unchanged
role.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection unchanged
role.rbac.authorization.k8s.io/percona-server-mysql-operator configured
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator-leaderelection unchanged
rolebinding.rbac.authorization.k8s.io/percona-server-mysql-operator unchanged
configmap/percona-server-mysql-operator-config created
deployment.apps/percona-server-mysql-operator created

$ kubectl get all
NAME                                                 READY   STATUS             RESTARTS   AGE
pod/percona-server-mysql-operator-77cb95b487-gvkmz   0/1     ImagePullBackOff   0          82s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   7d23h

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/percona-server-mysql-operator   0/1     1            0           82s

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/percona-server-mysql-operator-77cb95b487   1         1         0       82s


$ kubectl describe pod percona-server-mysql-operator-77cb95b487-67z2n


  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  61s                default-scheduler  Successfully assigned default/percona-server-mysql-operator-77cb95b487-67z2n to minikube
  Normal   Pulling    14s (x3 over 61s)  kubelet            Pulling image "perconalab/percona-server-mysql-operator:anel-try-to-build"
  Warning  Failed     12s (x3 over 59s)  kubelet            Failed to pull image "perconalab/percona-server-mysql-operator:anel-try-to-build": rpc error: code = Unknown desc = Error response from daemon: manifest for perconalab/percona-server-mysql-operator:anel-try-to-build not found: manifest unknown: manifest unknown
  Warning  Failed     12s (x3 over 59s)  kubelet            Error: ErrImagePull
  Normal   BackOff    1s (x3 over 59s)   kubelet            Back-off pulling image "perconalab/percona-server-mysql-operator:anel-try-to-build"
  Warning  Failed     1s (x3 over 59s)   kubelet            Error: ImagePullBackOff

$ kubectl get ps
NAME       MYSQL   ORCHESTRATOR   STATE   AGE
cluster1                                  117s
```

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-81/72bbfb2/users.log) |
| We run 8 out of 8|

commit: https://github.com/percona/percona-server-mysql-operator/pull/81/commits/72bbfb20d540e7bf995a351beb4e1cb750ca4182
image: `perconalab/percona-server-mysql-operator:PR-81-72bbfb2`

**Comment by egegunes** [comment]
@an3l currently you can override the image, squashing and caching like this:

```
DOCKER_SQUASH=0 DOCKER_NOCACHE=0 IMAGE=egegunes/percona-server-mysql-operator:main make build install deploy IMG=egegunes/percona-server-mysql-operator:main
```

your questions made me realize that our Makefile is not optimal and it's hard for other people to contribute our repo. I created a PR for improvements: https://github.com/percona/percona-server-mysql-operator/pull/84

**Review by egegunes — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
