### PR TITLE
K8SPS-60 use semi sync replication by default

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Review by spron-in — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/47/commits/aebffed3a9a66674875c324115860b722ecf5b8e
image: `perconalab/percona-server-mysql-operator:PR-47-aebffed`

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/47/commits/aebffed3a9a66674875c324115860b722ecf5b8e
image: `perconalab/percona-server-mysql-operator:PR-47-aebffed`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/47/commits/aebffed3a9a66674875c324115860b722ecf5b8e
image: `perconalab/percona-server-mysql-operator:PR-47-aebffed`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/47/commits/aebffed3a9a66674875c324115860b722ecf5b8e
image: `perconalab/percona-server-mysql-operator:PR-47-aebffed`

**Pull request closed without merging**
