### PR TITLE
K8SPS-66 - Add service-per-pod test

### PR DESCRIPTION
**Pull request by tplavcic**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | failed |
| sidecars | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/c0e15a5eb7a59f586aecd3b6d56334df5bc0c88f
image: `perconalab/percona-server-mysql-operator:PR-49-c0e15a5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | failed |
| sidecars | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/b0d800a4a9f46173d2c16bd61a057661c394e643
image: `perconalab/percona-server-mysql-operator:PR-49-b0d800a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/b0d800a4a9f46173d2c16bd61a057661c394e643
image: `perconalab/percona-server-mysql-operator:PR-49-b0d800a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/b0d800a4a9f46173d2c16bd61a057661c394e643
image: `perconalab/percona-server-mysql-operator:PR-49-b0d800a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | failed |
| sidecars | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/b0d800a4a9f46173d2c16bd61a057661c394e643
image: `perconalab/percona-server-mysql-operator:PR-49-b0d800a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | passed |
| sidecars | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/95482dffb00e5c779e7e832f1c1ff5fdda937fbc
image: `perconalab/percona-server-mysql-operator:PR-49-95482df`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | passed |
| sidecars | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/95482dffb00e5c779e7e832f1c1ff5fdda937fbc
image: `perconalab/percona-server-mysql-operator:PR-49-95482df`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | passed |
| init-deploy | passed |
| monitoring | passed |
| semi-sync | passed |
| service-per-pod | passed |
| sidecars | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/49/commits/233832a471601ac593ff040dd9a1199e5ce02a88
image: `perconalab/percona-server-mysql-operator:PR-49-233832a`

**Review by egegunes — APPROVED** [review]

**Pull request merged**
