### PR TITLE
Update versions for PSO 0.1.0 release

### PR DESCRIPTION
**Pull request by egegunes**

### CODE REVIEW

**Comment by tplavcic** [comment]
@egegunes Shouldn't this PR be pointed to release branch?

**Comment by tplavcic** [comment]
Do I get correctly that we will need to revert this commit on the main branch after release?

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/48/commits/5e54df71dd008adb00456dd69b7cb0b321caa548
image: `perconalab/percona-server-mysql-operator:PR-48-5e54df7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | failed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/48/commits/b95e53cd7fd955020037aa7066661b3c4ce0181c
image: `perconalab/percona-server-mysql-operator:PR-48-b95e53c`

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
