### PR TITLE
K8SPS-61: Rename CRD to PerconaServerMySQL

### PR DESCRIPTION
**Pull request by egegunes**
We're also changing the api version (from v2 to v1alpha1) of our CRD. It
may break the new deployments if the old CRDs installed in the cluster.

In case of any errors, delete the old ones:

```
kubectl delete crd perconaserverformysqls.ps.percona.com
kubectl delete crd perconaserverformysqlbackups.ps.percona.com
kubectl delete crd perconaserverformysqlrestores.ps.percona.com
```

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/45/commits/53291428cfd8d36699b40127c863c74ce80e8840
image: `perconalab/percona-server-mysql-operator:PR-45-5329142`

**Review by hors — COMMENTED** [review]
@egegunes please add task number to the PR

**Review by tplavcic — COMMENTED** [review]
In rbac.yaml our roles/rolesbindings are called like:

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| semi-sync | failed |
| monitoring | failed |
| sidecars | failed |
| config | failed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/45/commits/313bebcbbe261c9b294b6557f9833b846c44642b
image: `perconalab/percona-server-mysql-operator:PR-45-313bebc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| semi-sync | failed |
| monitoring | failed |
| sidecars | failed |
| config | failed |
| users | failed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/45/commits/fb662f97fc006a2fc3f7f71081ae0168d668696d
image: `perconalab/percona-server-mysql-operator:PR-45-fb662f9`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |
| config | passed |
| users | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/45/commits/8ab54f70dcdc1099d20508eefe1ac0172e33ea01
image: `perconalab/percona-server-mysql-operator:PR-45-8ab54f7`

**Comment by egegunes** [comment]
@tplavcic https://github.com/percona/percona-server-mysql-operator/pull/45/commits/8ab54f70dcdc1099d20508eefe1ac0172e33ea01

**Review by tplavcic — APPROVED** [review]

**Review by spron-in — APPROVED** [review]

**Pull request merged**
