### PR TITLE
K8SPS-125: cluster secret shouldn't be removed during CR deletion

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPS-125](https://jira.percona.com/browse/K8SPS-125) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPS-125

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/demand-backup.log) |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/auto-config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/init-deploy.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/service-per-pod.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/config.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/limits.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/users.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/169/commits/9624310a802af83aa44016df99892f56308b95dd
image: `perconalab/percona-server-mysql-operator:PR-169-9624310`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/auto-config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/init-deploy.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/config.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/gr-init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/demand-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/limits.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/scaling.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-169/9624310/users.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/169/commits/9624310a802af83aa44016df99892f56308b95dd
image: `perconalab/percona-server-mysql-operator:PR-169-9624310`

**Review by hors — CHANGES_REQUESTED** [review]
@pooknull now we remove `internal-cluster1` but leave `cluster1-secrets`. We should not remove both these secrets (as we do it in PXC operator.)

**Review by inelpandzic — COMMENTED** [review]
When I created the cluster I had:
```
➜  percona-server-mysql-operator git:(dev/K8SPS-125-fix-secret-deletion) ✗ k get secrets
NAME                                        TYPE                                  DATA   AGE
cluster1-secrets                            Opaque                                8      20m
cluster1-ssl                                kubernetes.io/tls                     3      20m
internal-cluster1                           Opaque                                8      20m
```
After deletion I can see only:
```
➜  percona-server-mysql-operator git:(dev/K8SPS-125-fix-secret-deletion) ✗ k get secrets
NAME                                        TYPE                                  DATA   AGE
cluster1-secrets                            Opaque                                8      21m
```
Should we delete the other two?

**Comment by hors** [comment]
> After deletion I can see only:
> 
> ```
> ➜  percona-server-mysql-operator git:(dev/K8SPS-125-fix-secret-deletion) ✗ k get secrets
> NAME                                        TYPE                                  DATA   AGE
> cluster1-secrets                            Opaque                                8      21m
> ```
> 
> Should we delete the other two?

@inelpandzic yes, we need to delete cluster1-ssl secret for now. In PXC operator we have smart logic connected with it, so we will implement the same for ps operator

**Comment by pooknull** [comment]
> @pooknull now we remove `internal-cluster1` but leave `cluster1-secrets`. We should not remove both these secrets (as we do it in PXC operator.)

https://github.com/percona/percona-server-mysql-operator/pull/169/commits/79f62cd5f0b9d44d85cc638bd2afa3c6aef2ad16

**Review by hors — APPROVED** [review]

**Review by inelpandzic — APPROVED** [review]

**Pull request merged**
