### PR TITLE
K8SPS-244 custom config auto pods restart

### PR DESCRIPTION
**Pull request by aaservice**
[K8SPS-244](https://jira.percona.com/browse/K8SPS-244) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

@Bndrs21 *CHANGE DESCRIPTION**
---
**Problem:**
*Short explanation of the problem.*

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [x] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [x] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [x] Is an E2E test/test case added for the new feature/change?
- [x] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [x] Are all needed new/changed options added to default YAML files?
- [x] Are the manifests (crd/bundle) regenerated if needed?
- [x] Did we add proper logging messages for operator actions?
- [x] Did we ensure compatibility with the previous version or cluster upgrade process?
- [x] Does the change support oldest and newest supported PS version?
- [x] Does the change support oldest and newest supported Kubernetes version?

[K8SPS-244]: https://perconadev.atlassian.net/browse/K8SPS-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by aaservice** [comment]
Q

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| async-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/async-ignore-annotations.log) |
| auto-config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/auto-config.log) |
| config | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/config.log) |
| config-router | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/config-router.log) |
| demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/demand-backup.log) |
| gr-bootstrap | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-bootstrap.log) |
| gr-demand-backup | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-demand-backup.log) |
| gr-ignore-annotations | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-ignore-annotations.log) |
| gr-init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-init-deploy.log) |
| gr-one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-one-pod.log) |
| gr-scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-scaling.log) |
| gr-tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/gr-tls-cert-manager.log) |
| haproxy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/haproxy.log) |
| init-deploy | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/init-deploy.log) |
| limits | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/limits.log) |
| monitoring | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/monitoring.log) |
| one-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/one-pod.log) |
| scaling | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/scaling.log) |
| semi-sync | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/semi-sync.log) |
| service-per-pod | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/service-per-pod.log) |
| sidecars | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/sidecars.log) |
| tls-cert-manager | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/tls-cert-manager.log) |
| users | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/users.log) |
| version-service | [skipped](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-498/42e3423/version-service.log) |
| We run 0 out of 24|

commit: https://github.com/percona/percona-server-mysql-operator/pull/498/commits/42e3423dc9f5c926cb5600bc170e7c711628c9be
image: `perconalab/percona-server-mysql-operator:PR-498-42e3423`

**Review by aaservice — COMMENTED** [review]
duckduckgo.com/?q=Check+out+TeamYouTube+on+X.%0Aupdates+%26+answers+from+the+team+bringing+you+YouTube%2C+helping+in%3A+english%2C+espa%C3%B1ol%2C+portugu%C3%AAs%2C+deutsch%2C+fran%C3%A7ais%2C+p%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9%2C+%E6%97%A5%E6%9C%AC%E8%AA%9E%2C+indonesian%2C+%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9%2C+%E0%A4%B9%E0%A4%BF%E0%A4%82%E0%A4%A6%E0%A5%80%2C+%ED%95%9C%EA%B5%AD%EC%96%B4&t=ddg_ios&atb=v399-1me&ko=-1&ia=web” duckduckgo:favorite=“true”>Check out TeamYouTube on X. updates &amp; answers from the team bringing you YouTube, helping in: english, español, português, deutsch, français, pусский, 日本語, indonesian, العربية, हिंदी, 한국어 at DuckDuckGo</A>

**Comment by inelpandzic** [comment]
Spam

**Pull request closed without merging**
