### PR TITLE
CLOUD-695_jenkinsfile_improvements

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/9392919/users.log) |
| We run 7 out of 10|

commit: https://github.com/percona/percona-server-mysql-operator/pull/70/commits/9392919e2ae9f4816053014a4062b71adacc48cc
image: `perconalab/percona-server-mysql-operator:PR-70-9392919`

**Review by tplavcic — CHANGES_REQUESTED** [review]
If we get information like `We run 7 out of 10` - what does that mean - should we merge or not?

**Comment by nmarukovich** [comment]
> If we get information like `We run 7 out of 10` - what does that mean - should we merge or not?

I fixed the regexp. I suppose in this case we need to check is everything ok with the PR. I added just for our information

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-70/334fcbe/users.log) |
| We run 7 out of 7|

commit: https://github.com/percona/percona-server-mysql-operator/pull/70/commits/334fcbe18759e9f5f205b941e99540b98b01c78a
image: `perconalab/percona-server-mysql-operator:PR-70-334fcbe`

**Review by cap1984 — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
